# Generated by Django 2.2.5 on 2020-07-23 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='titanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PassangerId', models.CharField(max_length=100)),
                ('Pclass', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Sex', models.CharField(max_length=100)),
                ('Fare', models.FloatField()),
                ('Ticket', models.CharField(max_length=100)),
                ('Cabin', models.CharField(max_length=100)),
                ('Embarked', models.CharField(max_length=100)),
                ('Survived', models.IntegerField(blank=True, null=True)),
                ('Sibsp', models.IntegerField()),
                ('Parch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='client_reate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('is_otp', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
