# Generated by Django 2.2.5 on 2020-07-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titanic_app', '0002_auto_20200724_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titanic',
            name='SibSp',
        ),
    ]
