# Generated by Django 2.2.5 on 2020-07-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanic_app', '0003_remove_titanic_sibsp'),
    ]

    operations = [
        migrations.AddField(
            model_name='titanic',
            name='SibSp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='titanic',
            name='Survived',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
