# Generated by Django 2.2.5 on 2020-07-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanic_app', '0005_auto_20200724_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanic',
            name='Pclass',
            field=models.IntegerField(),
        ),
    ]
